// Code generated by mockery v2.10.0. DO NOT EDIT.

package gondlr

import mock "github.com/stretchr/testify/mock"

// MockOption is an autogenerated mock type for the Option type
type MockOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: g
func (_m *MockOption) Execute(g *Gondlr) error {
	ret := _m.Called(g)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Gondlr) error); ok {
		r0 = rf(g)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
